name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Release Archive
        run: |
          tar -czf google-calendar-mcp-server.tar.gz dist/ package.json README.md LICENSE
          zip -r google-calendar-mcp-server.zip dist/ package.json README.md LICENSE

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            google-calendar-mcp-server.tar.gz
            google-calendar-mcp-server.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}